config/routes.rb
F2nstore::Application.routes.draw do |map|

  devise_for :users

  resource :home

  resources :users
  resources :events do
    collection do
      get :confirm_passcode
    end
    member do
      get :configuration, :attendee_list, :purchase, :confirm
    end
    resources :attendees do
      member do
        get :new_photo, :register
        post :upload_photo, :userservice
      end
      collection do
        get :register
      end
    end
  end

  get "home/index"

  match '/download' =>'home#download', :as => 'download'
  
  root :to => "home#index"

  

end

app/views/layouts/application.html.haml
!!!
%html
  / version: 1.2
  -# versions
    1.2 -- removed old links at bottom of page.
    1.1 -- changed to 128 bit AES key for config bundle.
  
  %head
    %title Face2Name Store
    %script{:type => "text/javascript", :src => "http://use.typekit.com/jhj8vgz.js" }
    %script{:type => "text/javascript"}
      try{Typekit.load();}catch(e){}
    = stylesheet_link_tag 'reset.css', 'grid.css', 'face2name.css', 'button.css', 'uniform.default.css'
    = javascript_include_tag 'jquery-1.4.2.min.js', 'jquery.uniform.min.js', 'jquery.color.js', 'jquery.jqModal.js', 'application.js'
    = csrf_meta_tag
    .container.container_12.clearfix#header
      - if controller.registering_attendee?
        #reg-title.tk-bree= @event.name
      - else
        %a{:href => '/'}
          %h1.tk-bree face2name
      - if user_signed_in?
        #user_status
          welcome
          = current_user.email
          |
          = link_to "sign out", destroy_user_session_path
        %ul.tk-bree#nav_links
          %li
            = link_to 'Home', home_index_path
          %li
            = link_to 'Events', events_path
          %li
            = link_to 'Downloads', download_path
          - if current_user && current_user.admin?
            %li
              = link_to 'Admin', users_path

    .clear
    .container.container_12.body
      = yield
      .grid_1
        .divider
      .grid_3.sidebar
        - if controller.registering_attendee?
          %h2.tk-bree
            Event Details
          %p
            %b Begins:
            = @event.not_before.strftime('%B %d, %Y')
            %br
            %b Ends:
            = @event.not_after.strftime('%B %d, %Y')

        - else
          - if @events or @event
            - if @event and @event.id
              %p
                %a.tk-bree{:href => url_for(url_for(event_attendees_path(@event)))} Manage Attendees
                %br
                Manage the attendees for #{@event.name}
            %p
              %a.tk-bree{:href => url_for(url_for(new_event_path()))} Create New Event
              %br
              Create and purchase a new event configuration.

          - if current_user and current_user.events.length > 0
            %p
              %a.tk-bree{:href => url_for(:controller => '/events')} Manage Events
              %br
              Manage your existing events.
      #footer